export const Label = {
  form: 'authentication-form',
  title: 'authentication-title',
  tabMail: 'authentication-tab-mail',
  tabPhone: 'authentication-tab-phone',
  inputMail: 'authentication-input-mail',
  inputPhone: 'authentication-input-phone',
  submit: 'authentication-submit',
  inputNumber: 'authentication-input-number',
  phoneCountry: 'authentication-phone-country',
  resendCode: 'authentication-resend-code',
  registration: 'authentication-registration',
  phoneInputCountrySearch: 'authentication-phone-input-country-search',
  phoneCountryOption: 'authentication-phone-country-option',
}
