export const Label = {
  form: 'authentication-form',
  title: 'authentication-title',
  tabMail: 'authentication-tab-mail',
  tabPhone: 'authentication-tab-phone',
  tabWrapper: 'authentication-tab-wrapper',
  inputMail: 'authentication-input-mail',
  inputPhone: 'authentication-input-phone',
  inputEncryptionKey: 'encryption-input-key',
  submit: 'authentication-submit',
  phoneCountry: 'authentication-phone-country',
  resendCode: 'authentication-resend-code',
  registration: 'authentication-registration',
  phoneInputCountrySearch: 'authentication-phone-input-country-search',
  phoneCountryOption: 'authentication-phone-country-option',
  inputError: 'authentication-input-error',
  phoneWrapper: 'authentication-phone-wrapper',
  messageConfirm: 'authentication-message-confirm',
  inputCode: 'authentication-input-code',
  encryptionLoading: 'encryption-loading',
  encryptionCode: 'encryption-code',
  encryptionEnable: 'encryption-enable',
  encryptionDisable: 'encryption-disable',
  encryptionDone: 'encryption-done',
  encryptionEnterKey: 'encryption-enter-key',
  encryptionKeySubmit: 'encryption-submit-key',
  encryptionError: 'encryption-error',
}

export const Text = {
  RegistrationMessage: 'A new account was created for you.',
  CodeSentMessage: 'Enter the code received in your mail below or confirm through the link.',
  CodeSentMessagePhone: 'Enter the code or confirm through the link received by text.',
  CodeInputPlaceholder: 'Code',
  LoadingButton: 'Loading...',
  MailInputPlaceholder: 'Mail',
  CodeExpiredError: 'Code expired, please try again.',
  UnknownError: 'An unknown error occurred.',
  InvalidPhoneNumberError: 'Please enter a valid phone number.',
  InvalidMailError: 'Please enter a valid mail address.',
  FilterCountriesInputPlaceholder: 'Filter Countries',
  PhoneInputPlaceholder: 'Phone',
  CodeResentMessage: 'A new code is being sent to you.',
  EncryptionNoToken: 'Not logged in.',
  EncryptionLoadingStatus: 'Checking encryption status...',
  EncryptionDisabling: 'Disabling encryption...',
  EncryptionEnabling: 'Enabling encryption...',
  EncryptionKeyGenerated:
    'An encryption key has been generated, please remember it and store it somewhere safe.',
  EncryptionClose: 'Done',
  EncryptionEnterKey: 'Encryption is enabled for your account, please enter the encryption key.',
  EncryptionInputPlaceholder: 'Please enter the key...',
  EncryptionSubmitKey: 'Submit Key',
}
