name: push

on:
  push:
    branches: [main]

jobs:
  plugin:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: plugin
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - run: npm run build
      - run: npm test
      - run: npm install -g npm@latest
      - uses: tobua/release-npm-action@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FOLDER: plugin
  playwright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
      # Install in root to ensure all workspace dependencies installed.
      - run: |
          cd ..
          npm install --legacy-peer-deps
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm test
