name: push

on:
  push:
    branches: [main]

jobs:
  plugin:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: plugin
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - run: bun run test
      - uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          FOLDER: plugin
  playwright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # Install in root to ensure all workspace dependencies installed.
      - run: |
          cd ..
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bun run test
